export const TOGGLE_SLIDE = 'TOGGLE_SLIDE'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'

export const GET_HOME_LIST = 'GET_HOME_LIST'
export const ADD_HOME_LIST = 'ADD_HOME_LIST'

export const GET_THEME_LIST = 'GET_THEME_LIST'
export const GET_THEME_CONTENT = 'GET_THEME_CONTENT'

export const GET_CUR_ARTICLE = 'GET_CUR_ARTICLE'
